### ISSUE TITLE
Use of express.io with Node v6.9.5 is deprecated and doesn't work

### ISSUE THREAD

**Issue by mirzahusadzic** [mapic/mapic#19]
The package express.io rely on older version of express which depends on connect and ends with error:
```
engine_1       | module.js:471
engine_1       |     throw err;
engine_1       |     ^
engine_1       | 
**engine_1       | Error: Cannot find module 'express/node_modules/connect'**
engine_1       |     at Function.Module._resolveFilename (module.js:469:15)
engine_1       |     at Function.Module._load (module.js:417:25)
engine_1       |     at Module.require (module.js:497:17)
engine_1       |     at require (internal/module.js:20:19)
engine_1       |     at Object.<anonymous> (/mapic/modules/engine/node_modules/express.io/lib/index.coffee:4:13)
engine_1       |     at Object.<anonymous> (/mapic/modules/engine/node_modules/express.io/lib/index.coffee:263:4)
engine_1       |     at Module._compile (module.js:570:32)
engine_1       |     at Object.require.extensions..coffee (/mapic/modules/engine/node_modules/express.io/node_modules/coffee-script/lib/coffee-script/coffee-script.js:30:21)
engine_1       |     at Module.load (module.js:487:32)
engine_1       |     at tryModuleLoad (module.js:446:12)
```
The engine/package.json references "express": "^4.14.0" to be installed!
But as of 4.0 express no longer depends on connect. 
See https://expressjs.com/en/guide/migrating-4.html

Furthermore, if one forces and installs connect to express/node_modules/ manually, it ends with deprecation warning:

**engine_1       | (node:34) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.**

and later with error (after logging in):
```
engine_1       | /mapic/modules/engine/node_modules/express.io/compiled/index.js:242
engine_1       |           request.session = new connect.session.Session(request, session);
engine_1       |                                                ^
engine_1       | 
**engine_1       | TypeError: Cannot read property 'Session' of undefined**
engine_1       |     at Socket.<anonymous> (/mapic/modules/engine/node_modules/express.io/compiled/index.js:242:48)
engine_1       |     at emitOne (events.js:96:13)
engine_1       |     at Socket.emit (events.js:188:7)
engine_1       |     at SocketNamespace.handlePacket (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/namespace.js:335:22)
engine_1       |     at Manager.onClientMessage (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/manager.js:518:38)
engine_1       |     at WebSocket.Transport.onMessage (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transport.js:369:20)
engine_1       |     at Parser.<anonymous> (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
engine_1       |     at emitOne (events.js:96:13)
engine_1       |     at Parser.emit (events.js:188:7)
engine_1       |     at finish (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:295:16)
engine_1       |     at Parser.expectHandler (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:306:15)
engine_1       |     at Parser.add (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:482:24)
engine_1       |     at Parser.expect (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:519:10)
engine_1       |     at Parser.<anonymous> (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:305:18)
engine_1       |     at Parser.add (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:482:24)
engine_1       |     at Parser.expect (/mapic/modules/engine/node_modules/express.io/node_modules/socket.io/lib/transports/websocket/hybi-16.js:519:10)
```
Seems that old version of socket.io which express.io depends on cause problems!

Possible solution: switch to express.oi (fork of express.io which uses modern socket.io)

Update _**modules/engine/package.json**_
```
-    "express.io": "^1.1.13",
+    "express.oi": "git+https://github.com/sibartlett/express.oi.git",
```

Update _**modules/engine/server/server.js**_
```
- var express = require('express.io');
+ var express = require('express.oi');
```

@knutole Sorry, I think this issue should be moved to https://github.com/mapic/engine

**Comment by knutole** [comment]
Hi again,

Indeed, this is an issue. Did you test your solution? Again, I'd be happy - more than happy, thrilled! - to include your PR! :) (Yes, issue belongs to engine, and PR should go there.)

Thanks again. May I ask what you're using the software for? I'm very happy to see it taken into use! 👍

**Comment by mirzahusadzic** [comment]
Hi Knut,

I have working server run at localhost with Node v6.9.5. Here is an [engine test](https://github.com/mapic/mapic/files/881585/engine_test.txt) report. I hope this test results are acceptable? Should I create PR?

btw. I'm really just testing the Mapic, to see how it works! ;-) I think you did a great job! 👍

**Comment by knutole** [comment]
Had problems with `express.oi` as well, so instead hacked with a symlink: https://github.com/mapic/engine/commit/27255ae73e9a1d63eebd317585ec06dc2d4ab876#diff-0432e9bd914a9ac74ddf5a6ce5e7c0d8R20
